language: cpp

sudo: required
dist: trusty

install: if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
      
before_script:
  - sudo apt-get update
  - sudo apt-get install libgoogle-glog-dev
  - sudo add-apt-repository ppa:ppsspp/cmake
  - sudo apt-get upgrade cmake
  - mkdir build && cd build
  - mkdir download && cd download
  - wget -O boost https://sourceforge.net/projects/boost/files/latest/download?source=directory
  - tar -jxf boost 
  - sudo cp -r boost/boost /usr/include/
  - wget http://launchpadlibrarian.net/315398098/libbison-dev_3.0.4.dfsg-1build1_amd64.deb
  - sudo dpkg -i libbison-dev_3.0.4.dfsg-1build1_amd64.deb
  - cd ..
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Release ..

script:
  - make
  - cd test
  - ./ophidian_tests
