language: cpp

sudo: required
dist: trusty

install: if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
      
before_script:
  - sudo apt-get update
  - sudo apt-get install libgoogle-glog-dev
  - mkdir build && cd build
  - mkdir download && cd download
  - wget http://launchpadlibrarian.net/286832767/cmake_3.5.1-1ubuntu3_amd64.deb 
  - sudo dpkg -i cmake_3.5.1-1ubuntu3_amd64.deb
  - wget http://launchpadlibrarian.net/293879907/libboost-all-dev_1.62.0.1_amd64.deb
  - sudo dpkg -i libboost-all-dev_1.62.0.1_amd64.deb
  - wget http://launchpadlibrarian.net/315398098/libbison-dev_3.0.4.dfsg-1build1_amd64.deb
  - sudo dpkg -i libbison-dev_3.0.4.dfsg-1build1_amd64.deb
  - cd ..
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Release ..

script:
  - make
  - cd test
  - ./ophidian_tests
