language: cpp

sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          packages:
            - libboost-all-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make -j && make test
