language: cpp

sudo: required
dist: trusty

compiler:
    - gcc

before_install:
  - mkdir boost
  - cd boost
  - wget https://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.bz2/download
  - tar jxf download
  - sudo cp -r boost_1_59_0/boost /usr/include/
  - cd ..
  - mkdir cmake
  - cd cmake
  - wget https://cmake.org/files/v3.6/cmake-3.6.1.tar.gz
  - tar -zxf cmake-3.6.1.tar.gz
  - cd cmake-3.6.1
  - ./configure
  - make
  - sudo make install
  - cd ../../

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && make test
