language: cpp

sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5


before_script:
  - sudo apt-get install libhash-multivalue-perl
  - sudo apt-get install gperf
  - mkdir build && cd build
  - wget https://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.bz2/download
  - tar jxf download
  - sudo cp -r boost_1_59_0/boost /usr/include/
  - wget http://ftp.gnu.org/gnu/bison/bison-3.0.4.tar.gz
  - tar -zxvf bison-3.0.4.tar.gz
  - cd bison-3.0.4
  - mkdir inst
  - ./configure --prefix=$PWD/inst
  - make -j && make install
  - cd inst/bin
  - export PATH=$PWD:$PATH
  - cd ..
  - cd ..
  - cd ..
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Release ..

script:
  - make -j 1
  - cd test
  - ./run_tests
